# 头部导航 Header
menu:
  首页: /
  归档: /archives

# 提供以下页面
#  首页: /
#  归档: /archives
#  关于: /about

rss: /atom.xml

# footer底部显示联系邮箱（在博客配置文件下添加email配置也是一样的效果）
email: 'wenhui-huang@qq.com'

# 内容 Content
excerpt_link: 阅读全文 »
fancybox: true

# 启用social widgets时有效
# 社交widget文本字体，不填写则不显示title
social_title: Follow me

# Social links 社交链接
social:
  github: https://github.com/michwh
  email: 'wenhui-huang@qq.com'

# 提供以下社交链接
# github
# weibo
# email
# zhihu

# 微信支付宝打赏
## 启用wechat widget才会生效，将图片放置在source文件夹下
wechat_url:  /wechat.png 
alipay_url: /alipay.jpg


# Friendly links 友情链接
links:
#Fan Fei's blog: https://michwh.github.io
  
# 是否带侧边栏 Sidebar
sidebar: true

# 文章底部推荐文章数,false关闭
random_posts: false

widgets:
- social
- post_content
- tagcloud
- wechat


# 提供以下内置组件
# - post_content      # 文章目录
# - category          # 归类
# - tag               # 标签
# - tagcloud          # 云标签
# - archives          # 归档
# - recent_posts      # 最新文章
# - lastest_comments  # 最新评论
# - hot_comment_posts # 热评文章
# - friendly_link     # 友情链接
# - wechat            # 打赏


# widget behavior
archive_type: 'monthly'

# 分类是否显示文章数量
show_count: true

# 标签云TagClound
# 如果启动，则标签云颜色为随机
tagcloud_color: false

# MathJax Support 显示数学公式
# 设置enable属性为true即可开启mathjax
# per_page如果为true表示所有文章都设置支持mathjax，如果为false，则在需要支持mathjax的文章加上mathjax: true
mathjax:
  enable: true
  per_page: false
  cdn: https://cdn.rawgit.com/mathjax/MathJax/2.7.1/MathJax.js?config=TeX-AMS-MML_HTMLorMML



# 其他参数
google_analytics:

# 图标，在source文件夹下
favicon: /favicon.ico


# comments 评论插件
# 关闭统一为 false

## 网易云跟帖
### 使用说明 http://cafe.giscafer.com/2017/04/14/gentie-test/
gentie_productKey: false

## 畅言 (不使用请将appid和appkey都设空或者false)
### 使用说明：http://changyan.kuaizhan.com/static/help/
changyan_appid: false  ##appid
changyan_appkey: false  ##appkey
## 友言
### 使用说明
### 填写友言用户ID http://www.uyan.cc/sites
youyan_uid: false

# gitment
## 教程：https://imsun.net/posts/gitment-introduction/ 网站上进行查看
gitment:
  enable: false #如果不使用则设置false关闭
  owner:  # 你的github名称或者id id的获取方式为https://api.github.com/users/forvoid（你的名称）中的id极为github id
  repo:  # 你的留言存放的位置 我的是放在我的github的github page上面
  client_id:  # Register a new OAuth application https://github.com/settings/applications/new 
  client_secret: 

## disqus
disqus_shortname: false

google_plus:
fb_admins:
fb_app_id:

